version: '3.8'

services:
  backend:
    build: ./backend
    container_name: ai-trading-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: ai-trading-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
