mode: "paper"  # "live" or "paper"

paper_trading:
  broker: "alpaca"
  api_key: "CKPV7LIKBVTQXIH2A3KN"
  api_secret: "YE6bChwKCkK9gU5WJwfM0alc44cEruIQNiOCAMG"
  base_url: "https://paper-api.alpaca.markets"

stop_loss: 0.02
take_profit: 0.05
trailing_stop: 0.01
